name: tldrnews_app
description: "A Video Player for TLDR News"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  #Core
  go_router: ^17.2.0
  shared_preferences: ^2.5.5
  web: ^1.1.1

  # Video Player
  youtube_player_iframe: ^5.2.2
  youtube_player_iframe_web: ^3.1.2
  webview_flutter: ^4.13.1
  webview_flutter_android: ^4.11.0
  webview_flutter_wkwebview: ^3.24.3
  video_player: ^2.11.1
  chewie: ^1.13.0

  # Firebase
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  firebase_analytics: ^12.2.0
  firebase_app_check: ^0.4.2
  firebase_remote_config: ^6.2.0
  google_sign_in: ^7.1.1

  # Config
  flutter_dotenv: ^5.2.1

  # UX
  phosphor_flutter: ^2.1.0
  json_annotation: ^4.11.0
  http: ^1.2.0
  flutter_linkify: ^6.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.13.0
  build_runner: ^2.13.0
  source_gen: ^4.0.0
  build: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/auth/
    - assets/logos/
    - assets/backgrounds/
    - .env
  fonts:
    - family: Assistant
      fonts:
        - asset: assets/fonts/Assistant-VariableFont_wght.ttf
    - family: Figtree
      fonts:
        - asset: assets/fonts/Figtree-VariableFont_wght.ttf
        - asset: assets/fonts/Figtree-Italic-VariableFont_wght.ttf
          style: italic
